/**
 * Every scan of a printed QR code passes through here: the scan is recorded,
 * then the visitor is sent on to the real page.
 *
 * Why a function instead of a plain CDN redirect. A static 302 costs ~10 ms and
 * is free, but the only evidence a scan happened is whatever the browser
 * reports afterwards — a GA4 hit that never fires if the person closes the page
 * during load, blocks trackers, is on a locked-down corporate phone, or has no
 * signal by the time the JS parses. On offline print that is not a rounding
 * error: it is routinely 10–30% of scans, and it is biased (the people who
 * bounce fastest are exactly the ones who vanish). Counting server-side, before
 * the redirect is even issued, makes the number what it claims to be: how many
 * times the paper was actually scanned.
 *
 * The redirect is the contract. Recording is best-effort and never blocks it:
 * every failure path below still ends in a 302, because a broken analytics
 * store must not turn a thousand printed cards into a dead link.
 *
 * Functions v2 (Request/Response), unlike brief.mjs which predates it — v2 is
 * what exposes context.geo and context.ip, and those are the two fields worth
 * having on a scan.
 *
 * Routing lives in dist/_redirects, generated by scripts/qr-redirects.mjs.
 */
import { createHash, randomUUID } from 'node:crypto';

import { getStore } from '@netlify/blobs';

import { QR_CODES, SITE, UTM_SOURCE, targetUrl } from '../../src/data/qrCodes.mjs';

const BY_CODE = new Map(QR_CODES.map((entry) => [entry.code, entry]));

export const STORE_NAME = 'qr-scans';

/**
 * How long the write gets before we give up and redirect anyway.
 *
 * A scan that goes uncounted is a small loss; a visitor staring at a blank tab
 * because the blob store is slow today is a real one. 1.5s is far above the
 * normal write (~30–80 ms) and far below the point where anyone assumes the
 * link is broken.
 */
const WRITE_TIMEOUT_MS = 1500;

/**
 * Requests that are not a person scanning a code.
 *
 * Link-preview fetchers are the ones that actually matter here: paste
 * sintara.io/qr1 into WhatsApp or Telegram and their crawler hits the URL
 * immediately, which without this filter shows up as a scan that never
 * happened — and it happens most often while testing the code, so the very
 * first numbers would be the wrong ones.
 */
const BOT_UA =
  /bot\b|crawler|spider|crawl|slurp|facebookexternalhit|whatsapp|telegrambot|twitterbot|discordbot|skypeuripreview|preview|monitor|pingdom|uptime|curl|wget|python-requests|axios|okhttp|go-http|java\/|headless|lighthouse|gtmetrix|pagespeed|semrush|ahrefs|screaming/i;

/** Codes are ours and always [a-z0-9-]; anything else is someone probing. */
const sanitize = (raw) =>
  String(raw ?? '')
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '')
    .slice(0, 32);

export default async (req, context) => {
  const url = new URL(req.url);

  // The rule passes the code explicitly (?code=qr1). The wildcard rule that
  // catches unregistered codes builds it from Netlify's :splat placeholder, so
  // guard against the placeholder arriving unsubstituted — that would silently
  // file every unknown scan under the literal string "qrsplat".
  const raw = url.searchParams.get('code') ?? '';
  const code = raw.includes(':') ? '' : sanitize(raw);
  const entry = code ? BY_CODE.get(code) : undefined;

  // Origin from the request, not the hardcoded domain: on a deploy preview this
  // keeps the visitor inside the preview instead of bouncing them to
  // production, which would make the code untestable before it is printed.
  const origin = url.origin.startsWith('http') ? url.origin : SITE;

  const destination = entry
    ? `${origin}${targetUrl(entry)}`
    : // An unregistered code is a real person holding real paper: a typo, a
      // retired tirage, a number someone guessed. Send them to the homepage
      // rather than a 404, tagged so the mismatch is visible in the report.
      `${origin}/?utm_source=${UTM_SOURCE}&utm_medium=unknown&utm_campaign=${
        code ? encodeURIComponent(code) : 'qr-unknown'
      }&utm_content=unregistered`;

  try {
    await withTimeout(record({ code: code || 'qr-unknown', entry, req, context }));
  } catch (error) {
    // Logged, never surfaced. The visitor gets their page either way.
    console.error('qr: failed to record scan', code, error);
  }

  return new Response(null, {
    status: 302,
    headers: {
      Location: destination,
      // Without this the CDN or the phone's browser is free to cache the 302 —
      // and a cached redirect skips this function entirely, so the second scan
      // of the same card by the same person would never be counted. The whole
      // point of routing through a function is lost to an HTTP default.
      'Cache-Control': 'no-store, no-cache, must-revalidate, max-age=0',
      'X-Robots-Tag': 'noindex',
    },
  });
};

/**
 * Writes one blob per scan.
 *
 * Append-only, one key per event, rather than incrementing a counter: blob
 * stores have no atomic increment, so two people scanning within the same
 * moment would read the same number, add one, and write the same result — one
 * scan quietly lost. Distinct keys can't collide, and they keep the detail
 * (when, where, which code) that a single number throws away.
 *
 * The key itself carries everything the report needs:
 *
 *   qr1/2026-09-05/TH/6f3a90c2b1d4-142731-8kq2
 *   code date       country visitor    time   nonce
 *
 * so scripts and the stats page aggregate by listing keys — no fetching
 * thousands of values to count them. The JSON value holds the rest, for when a
 * number looks strange and you want to see what actually arrived.
 */
const record = async ({ code, entry, req, context }) => {
  if (req.method === 'HEAD') return;

  const ua = req.headers.get('user-agent') ?? '';
  if (BOT_UA.test(ua)) return;

  // Browsers and messengers speculatively fetch links before anyone taps them.
  const purpose = `${req.headers.get('sec-purpose') ?? ''} ${req.headers.get('purpose') ?? ''}`;
  if (purpose.includes('prefetch') || purpose.includes('prerender')) return;

  const now = new Date();
  const { date, time } = localStamp(now);
  const country = (context.geo?.country?.code ?? 'XX').toUpperCase().slice(0, 2);

  const store = getStore(STORE_NAME);
  await store.set(
    `${code}/${date}/${country}/${visitorId(context.ip, ua, date)}-${time}-${randomUUID().slice(0, 4)}`,
    JSON.stringify({
      code,
      at: now.toISOString(),
      country,
      city: context.geo?.city ?? null,
      to: entry ? entry.to : '/',
      medium: entry ? entry.medium : 'unknown',
      content: entry ? entry.content : 'unregistered',
      referrer: (req.headers.get('referer') ?? '').slice(0, 200),
      language: (req.headers.get('accept-language') ?? '').slice(0, 40),
      ua: ua.slice(0, 200),
    }),
  );
};

/**
 * The day a scan belongs to, in the studio's own timezone rather than UTC.
 *
 * Netlify runs in UTC, which in Phuket puts everything between 7am and 2pm
 * local on the wrong side of midnight — hand out cards at a morning event and
 * half the scans would be filed under the previous day. Nobody reads a report
 * in UTC, so the day boundary is drawn where the person reading it lives.
 * QR_TIMEZONE overrides it; the exact instant is kept in the record as UTC ISO
 * either way, so nothing is lost if this ever changes.
 */
const TIMEZONE = process.env.QR_TIMEZONE || 'Asia/Bangkok';

export const localStamp = (now) => {
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone: TIMEZONE,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    // h23, not hour12:false — the latter renders midnight as "24" on some ICU
    // builds, which would sort every midnight scan after the following day.
    hourCycle: 'h23',
  })
    .formatToParts(now)
    .reduce((acc, part) => ({ ...acc, [part.type]: part.value }), {});

  return {
    date: `${parts.year}-${parts.month}-${parts.day}`,
    time: `${parts.hour}${parts.minute}${parts.second}`,
  };
};

/**
 * A per-day pseudonym, so "12 scans" can be separated from "12 people".
 *
 * The IP is hashed and never stored, and the date is part of the input — which
 * means the same phone gets a different id tomorrow and the ids cannot be
 * joined across days into a trail. That is deliberate: the question worth
 * answering is "how many different people scanned this card today", not "which
 * person came back". It also keeps this on the right side of GDPR without a
 * consent prompt, matching how the rest of the site is built (see lib/consent).
 */
const visitorId = (ip, ua, date) =>
  createHash('sha256').update(`${ip ?? ''}|${ua}|${date}|sintara-qr`).digest('hex').slice(0, 12);

const withTimeout = (promise) =>
  Promise.race([
    promise,
    new Promise((_, reject) =>
      setTimeout(() => reject(new Error('blob write timed out')), WRITE_TIMEOUT_MS),
    ),
  ]);
